[workspace]
resolver = "3"
members = ["crates/wayfarer-core", "crates/wayfarer-cli"]
default-members = ["crates/wayfarer-cli"]

[workspace.package]
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
tracing = "0.1"

[workspace.lints.clippy]
pedantic = "deny"
nursery = "deny"
unwrap_used = "deny"
expect_used = "deny"
enum_glob_use = "deny"
