name: CI
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Filter Changes
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            rust:
              - '**.rs'
              - '**/Cargo.toml'
              - 'Cargo.lock'
              - 'rust-toolchain.toml'
              - 'rust-toolchain'

      - name: Setup Rust toolchain
        if: steps.filter.outputs.rust == 'true'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install nextest
        if: steps.filter.outputs.rust == 'true'
        uses: taiki-e/install-action@nextest

      - name: Setup sccache
        if: steps.filter.outputs.rust == 'true'
        uses: mozilla-actions/sccache-action@v0.0.10
        with:
          version: "v0.14.0"
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"

      - name: Restore cargo & target cache
        if: steps.filter.outputs.rust == 'true'
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-ci
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Format
        if: steps.filter.outputs.rust == 'true'
        env:
          RUSTC_WRAPPER: sccache
          SCCACHE_GHA_ENABLED: "true"
        run: cargo fmt --check

      - name: Lint
        if: steps.filter.outputs.rust == 'true'
        env:
          RUSTC_WRAPPER: sccache
          SCCACHE_GHA_ENABLED: "true"
        run: cargo clippy

      - name: Build
        if: steps.filter.outputs.rust == 'true'
        env:
          RUSTC_WRAPPER: sccache
          SCCACHE_GHA_ENABLED: "true"
        run: cargo build --release

      - name: Run tests
        if: steps.filter.outputs.rust == 'true'
        env:
          RUSTC_WRAPPER: sccache
          SCCACHE_GHA_ENABLED: "true"
        run: cargo nextest run --release --workspace --all-features

      - name: sccache stats
        if: steps.filter.outputs.rust == 'true'
        run: sccache --show-stats || true
